# introduction to pandas

In [1]:
import pandas as pd

In [ ]:
#in pandas, we have two main data types
#1.series
series =pd.Series(["BMW", "Toyota", "Honda"])

In [3]:
series

0       BMW
1    Toyota
2     Honda
dtype: object

In [ ]:
#series = 1 dimensional

In [7]:
#one more 1D example
color =pd.Series(["Green", "Red", "Blue", "black"])

In [9]:
#2. dataframe = 2-dimensional
car_data = pd.DataFrame({"car_make": series, "color": color})#you can make DataFrames from Series datatypes

In [11]:
car_data #illustration of 2d data made from the conjunction of 1d data

  car_make  color
0      BMW  Green
1   Toyota    Red
2    Honda   Blue
3      NaN  black

In [ ]:
#importing data
car_sales =pd.read_csv("data/1 car-sales.csv")

In [ ]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In pandas, we can have rows and columns. The rows start fom index 0, just like python. The Rowas are called axis =0 and the columns are called axis =1. The rowa run from left to right while the columns run from top to bottom.

## Describe data

In [16]:
#attribute-the methods are without brackets
car_sales.dtypes #this gives the data types of the comlums of the dataframe

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [18]:
car_sales.columns #prints the columns of the dataframe

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [19]:
car_sales.describe()#a function, not attribute-this brings the summary for columns with numerical datatypes

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [ ]:
car_sales.info( ) #gives  the general info about the dataframe
print(car_sales["Doors"].sum())#gives the sum of the column specified --should return 40
len(car_sales)#gives you the total count of rows in the datafram--should return 10

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes
40

10